image: node:16.20.2

pipelines:
  branches:
    uat:
      - step:
          name: Deploy Test
          deployment: test
          script:
            - npm install
            - npm run build
            - pipe: atlassian/aws-s3-deploy:0.4.3
              variables:
                S3_BUCKET: "$BUCKET_NAME/docs"
                LOCAL_PATH: "build"
            - pipe: atlassian/aws-cloudfront-invalidate:0.3.2
              variables:
                DISTRIBUTION_ID: "$DISTRIBUTION_ID"
                PATHS: "/docs/*"
    master:
      - step:
          name: Deploy Production
          deployment: production
          script:
            - npm install
            - npm run build
            - pipe: atlassian/aws-s3-deploy:0.4.3
              variables:
                S3_BUCKET: "$BUCKET_NAME/docs"
                LOCAL_PATH: "build"
            - pipe: atlassian/aws-cloudfront-invalidate:0.3.2
              variables:
                DISTRIBUTION_ID: "$DISTRIBUTION_ID"
                PATHS: "/docs/*"
