image: node:10.15.3

definitions:
  steps:
    - step: &deploy-s3
        name: Deploy to S3
        caches:
          - node
        script:
          - npm install
          - npm run build
          - pipe: atlassian/aws-s3-deploy:0.4.3
            variables:
              S3_BUCKET: "$BUCKET_NAME"
              LOCAL_PATH: "build"
          - pipe: atlassian/aws-cloudfront-invalidate:0.3.2
            variables:
              DISTRIBUTION_ID: "$DISTRIBUTION_ID"
              PATHS: "/*"
pipelines:
  branches:
    uat:
      - step:
      - step:
          <<: *deploy-s3
          name: Deploy S3 Test
          deployment: test
    master:
      - step:
          <<: *deploy-s3
          name: Deploy S3 Production
          deployment: production
