image: node:10.15.3

definitions:
  steps:
    - step: &deploy-s3
        name: Deploy to S3
        caches:
          - node
        script:
          - pipe: atlassian/aws-s3-deploy:0.4.3
            variables:
              S3_BUCKET: "$BUCKET_NAME/docs"
              LOCAL_PATH: "build"
          - pipe: atlassian/aws-cloudfront-invalidate:0.3.2
            variables:
              DISTRIBUTION_ID: "$DISTRIBUTION_ID"
              PATHS: "/docs/*"
pipelines:
  branches:
    uat:
      - step:
          name: Build test site
          script:
            - npm install
            - npm run build:uat
      - step:
          <<: *deploy-s3
          name: Deploy S3
          deployment: test
    master:
      - step:
          name: Build production site
          script:
            - npm install
            - npm run build:uat
      - step:
          <<: *deploy-s3
          name: Deploy S3
          deployment: production
