image: node:10.15.3

pipelines:
  branches:
    uat:
      - step:
          deployment: test
          caches:
            - node
          script:
            - npm install
            - npm run build
            - pipe: atlassian/aws-s3-deploy:0.4.3
              variables:
                S3_BUCKET: "$BUCKET_NAME"
                LOCAL_PATH: "build"
            - pipe: atlassian/aws-cloudfront-invalidate:0.1.1
              variables:
                DISTRIBUTION_ID: "EDTJ9RZYTIO05"
                PATHS: "/index.html /assets/*"
    master:
      - step:
          deployment: production
          caches:
            - node
          script:
            - npm install
            - npm run build
            - pipe: atlassian/aws-s3-deploy:0.4.3
              variables:
                S3_BUCKET: "$BUCKET_NAME"
                LOCAL_PATH: "build"
            - pipe: atlassian/aws-cloudfront-invalidate:0.1.1
              variables:
                DISTRIBUTION_ID: "EDTJ9RZYTIO05"
                PATHS: "/index.html /assets/*"
