module.exports = {
    someSidebar: {
        Android: [
            'android/setup',
            'android/invoke',
            'android/disable',
            'android/silent-reports',
            'android/inspect',
            'android/screenshot',
            'android/permissions',
            'android/activity',
            'android/essentials',
            'android/attachments',
            'android/blackbox',
            'android/metadata',
            'android/quick-facts',
        ],
        iOS: ['doc1', 'doc2', 'doc3'],
        "React Native": [
            'react/setup',
            'react/invoke',
            'react/disable',
            'react/inspect',
            'react/screenshot',
            'react/permissions',
            'react/activity',
            'react/essentials',
            'react/attachments',
            'react/quick-facts',
        ],
    },
};
